import javax.swing.JCheckBox;
import java.sql.*;
import java.util.List;
import java.util.ArrayList;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
 import javax.swing.table.TableModel;

/**
 *
 * @author ASUS VivoBook
 */
public class FormDataDiri extends javax.swing.JFrame {

    /**
     * Creates new form FormDataDiri
     */
    public FormDataDiri() {
        initComponents();
        loadDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabelForm = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rb_jk_laki = new javax.swing.JRadioButton();
        rb_jk_perempuan = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        cmb_agama = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        txt_notelp = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        jPanelHobi = new javax.swing.JPanel();
        cb_hobi_makan = new javax.swing.JCheckBox();
        cb_hobi_film = new javax.swing.JCheckBox();
        cb_hobi_olahraga = new javax.swing.JCheckBox();
        cb_hobi_tidur = new javax.swing.JCheckBox();
        cb_hobi_game = new javax.swing.JCheckBox();
        cb_hobi_baca_buku = new javax.swing.JCheckBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBio = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();
        JButtonDelete = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelForm.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelForm.setText("FORM BIODATA");

        jLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel.setText("Nama Lengkap");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Jenis Kelamin");

        rb_jk_laki.setText("Laki - laki");
        rb_jk_laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_jk_lakiActionPerformed(evt);
            }
        });

        rb_jk_perempuan.setText("Perempuan");
        rb_jk_perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_jk_perempuanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Agama");

        cmb_agama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Buddha", "Konghucu", " " }));
        cmb_agama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_agamaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Hobi");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("No Telepon");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Alamat");

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        cb_hobi_makan.setText("Makan");
        cb_hobi_makan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hobi_makanActionPerformed(evt);
            }
        });

        cb_hobi_film.setText("Nonton Film");
        cb_hobi_film.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hobi_filmActionPerformed(evt);
            }
        });

        cb_hobi_olahraga.setText("Olahraga");
        cb_hobi_olahraga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hobi_olahragaActionPerformed(evt);
            }
        });

        cb_hobi_tidur.setText("Tidur");
        cb_hobi_tidur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hobi_tidurActionPerformed(evt);
            }
        });

        cb_hobi_game.setText("Game");
        cb_hobi_game.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hobi_gameActionPerformed(evt);
            }
        });

        cb_hobi_baca_buku.setText("Baca Buku");
        cb_hobi_baca_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_hobi_baca_bukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelHobiLayout = new javax.swing.GroupLayout(jPanelHobi);
        jPanelHobi.setLayout(jPanelHobiLayout);
        jPanelHobiLayout.setHorizontalGroup(
            jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHobiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_hobi_olahraga, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(cb_hobi_makan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHobiLayout.createSequentialGroup()
                        .addComponent(cb_hobi_film, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addComponent(cb_hobi_tidur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHobiLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(cb_hobi_baca_buku, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(jPanelHobiLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cb_hobi_game, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelHobiLayout.setVerticalGroup(
            jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHobiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_hobi_makan)
                    .addComponent(cb_hobi_film)
                    .addComponent(cb_hobi_game))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelHobiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_hobi_olahraga)
                    .addComponent(cb_hobi_tidur, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_hobi_baca_buku))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTableBio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama_Lengkap", "Jenis_Kelamin", "Agama", "Hobi", "Email", "No_Telp", "Alamat", "CreatedDate", "UpdatedDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableBio);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("DATA BIODATA");

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        JButtonDelete.setText("Delete");
        JButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(rb_jk_laki)
                                            .addGap(18, 18, 18)
                                            .addComponent(rb_jk_perempuan))
                                        .addComponent(txt_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txt_email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(txt_notelp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(txt_alamat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                        .addComponent(cmb_agama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jPanelHobi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(jLabelForm)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_simpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_tambah)
                        .addGap(68, 68, 68)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(13, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(JButtonDelete)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelForm)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEdit)
                            .addComponent(JButtonDelete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel)
                            .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rb_jk_laki)
                            .addComponent(rb_jk_perempuan))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmb_agama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jPanelHobi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_notelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_simpan)
                            .addComponent(btn_tambah)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_jk_lakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_jk_lakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_jk_lakiActionPerformed

    private void rb_jk_perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_jk_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_jk_perempuanActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // TODO add your handling code here:
        try {
            int i = jTableBio.getSelectedRow();
            TableModel mdl = jTableBio.getModel();

            // ArrayList untuk menampung hobi yang dipilih
            ArrayList<String> hobiArr = new ArrayList<>();
            // Iterasi semua komponen di dalam panel
            for (java.awt.Component comp : jPanelHobi.getComponents()) {
                if (comp instanceof JCheckBox checkbox) { // Cek apakah komponen adalah JCheckBox
                    if (checkbox.isSelected()) { // Cek apakah checkbox dipilih
                        hobiArr.add(checkbox.getText()); // Tambahkan teks checkbox ke array
                    }
                }
            }

            // Join text delimiter ","
            String hobi = String.join(",", hobiArr);

            // Set variables
            Biodata bd = new Biodata();
            bd.setId_biodata((int) mdl.getValueAt(i, 0));
            bd.setNama_lengkap(txt_nama.getText());
            bd.setJenis_kelamin(rb_jk_laki.isSelected() ? "L" : "P");
            bd.setAgama(cmb_agama.getSelectedItem().toString());
            bd.setAlamat(txt_alamat.getText());
            bd.setEmail(txt_email.getText());
            bd.setHobi(hobi);
            bd.setNo_telp(txt_notelp.getText());

            BiodataDAO dao = new BiodataDAO();
            String upd = dao.updateBiodata(bd);

            JOptionPane.showMessageDialog(rootPane, upd, "Success", HEIGHT);
            reset();
            loadDataToTable();
        } catch (SQLException ex) {
            Logger.getLogger(FormBiodata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        try {
            // ArrayList to store selected hobbies
            ArrayList<String> hobiArr = new ArrayList<>();
            // Iterate through all components in the panel
            for (java.awt.Component comp : jPanelHobi.getComponents()) {
                if (comp instanceof JCheckBox checkbox) { // Check if the component is a JCheckBox
                    if (checkbox.isSelected()) { // Check if the checkbox is selected
                        hobiArr.add(checkbox.getText()); // Add checkbox text to the array
                    }
                }
            }
    
            // Join text with delimiter ","
            String hobi = String.join(",", hobiArr);
    
            // Set variables
            Biodata bd = new Biodata();
            bd.setNama_lengkap(txt_nama.getText());
            bd.setJenis_kelamin(rb_jk_laki.isSelected() ? "L" : "P");
            bd.setAgama(cmb_agama.getSelectedItem().toString());
            bd.setAlamat(txt_alamat.getText());
            bd.setEmail(txt_email.getText());
            bd.setHobi(hobi);
            bd.setNo_telp(txt_notelp.getText());
    
            BiodataDAO dao = new BiodataDAO();
            String ins = dao.insert(bd);
    
            JOptionPane.showMessageDialog(rootPane, ins, "Success", HEIGHT);
    
            loadDataToTable();
            reset();
        } catch (SQLException ex) {
            Logger.getLogger(FormBiodata.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void cmb_agamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_agamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_agamaActionPerformed

    private void cb_hobi_makanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hobi_makanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hobi_makanActionPerformed

    private void cb_hobi_filmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hobi_filmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hobi_filmActionPerformed

    private void cb_hobi_olahragaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hobi_olahragaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hobi_olahragaActionPerformed

    private void cb_hobi_tidurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hobi_tidurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hobi_tidurActionPerformed

    private void cb_hobi_gameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hobi_gameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hobi_gameActionPerformed

    private void cb_hobi_baca_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_hobi_baca_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_hobi_baca_bukuActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        int i = jTableBio.getSelectedRow();

        TableModel mdl = jTableBio.getModel();
    
        jLabelForm.setText("Edit Data ID : " + mdl.getValueAt(i, 0).toString());
    
        txt_nama.setText(mdl.getValueAt(i, 1).toString());
    
        if(mdl.getValueAt(i, 2).toString().equals("Perempuan")){
            rb_jk_perempuan.setSelected(true);
        } else {
            rb_jk_laki.setSelected(true);
        }
    
        cmb_agama.setSelectedItem(mdl.getValueAt(i, 3).toString());
    
        String[] hobi = mdl.getValueAt(i, 4).toString().split(",");
    
        for (String hobi1 : hobi) {
            for (java.awt.Component comp : jPanelHobi.getComponents()) {
                if (comp instanceof JCheckBox checkbox) { // Check if component is a JCheckBox
                    if (checkbox.getText().equals(hobi1)) { // Check if checkbox text matches
                        checkbox.setSelected(true); // Select the checkbox
                    }
                }
            }
        }
    
        txt_email.setText(mdl.getValueAt(i, 5).toString());
        txt_notelp.setText(mdl.getValueAt(i, 6).toString());
        txt_alamat.setText(mdl.getValueAt(i, 7).toString());
    
        btn_tambah.setEnabled(false);
        btn_simpan.setEnabled(true);
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void JButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonDeleteActionPerformed
        // TODO add your handling code here:
        int response = JOptionPane.showConfirmDialog(null,
            "Anda yakin menghapus data ini?",
            "Konfirmasi Hapus Data",
            JOptionPane.OK_CANCEL_OPTION);
    
        int i = jTableBio.getSelectedRow();
    
        TableModel mdl = jTableBio.getModel();
    
        if (response == JOptionPane.OK_OPTION) {
            try {
                BiodataDAO dao = new BiodataDAO();
                String del = dao.deleteBiodata((int) mdl.getValueAt(i, 0));
    
                JOptionPane.showMessageDialog(rootPane, del, "Success", HEIGHT);
                loadDataToTable();
                reset();
            } catch (SQLException ex) {
                Logger.getLogger(FormBiodata.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_JButtonDeleteActionPerformed

    private void reset() {
        txt_alamat.setText("");
        txt_email.setText("");
        txt_nama.setText("");
        txt_notelp.setText("");
        cmb_agama.setSelectedIndex(0);

        rb_jk_laki.setSelected(false);
        rb_jk_perempuan.setSelected(false);

        btn_tambah.setEnabled(true);
        btn_simpan.setEnabled(false);
        jLabelForm.setText("FORM BIODATA");

        for (java.awt.Component comp : jPanelHobi.getComponents()) {
            if (comp instanceof JCheckBox checkbox) { // Check if component is a JCheckBox
                if (checkbox.isSelected()) { // Check if checkbox is selected
                    checkbox.setSelected(false);
                }
            }
        }
    }

    private void loadDataToTable() {
        try {
            // Initialize BiodataDAO object
            BiodataDAO dao = new BiodataDAO();
            // Initialize variable to hold data from the database
            List<ArrayList> biodataList = dao.readBiodata();
            // Initialize JTable model
            DefaultTableModel model = (DefaultTableModel) jTableBio.getModel();
            model.setRowCount(0); // Clear all rows

            for (ArrayList biodata : biodataList) {
                String jk = biodata.get(2).equals("P") ? "Perempuan" : "Laki-Laki";
                Object[] row = {
                    biodata.get(0), biodata.get(1), jk,
                    biodata.get(3), biodata.get(4),
                    biodata.get(5), biodata.get(6),
                    biodata.get(7), biodata.get(8),
                    biodata.get(9)
                };
                model.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data: " + e.getMessage());
        }
    }


        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataDiri().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonDelete;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JCheckBox cb_hobi_baca_buku;
    private javax.swing.JCheckBox cb_hobi_film;
    private javax.swing.JCheckBox cb_hobi_game;
    private javax.swing.JCheckBox cb_hobi_makan;
    private javax.swing.JCheckBox cb_hobi_olahraga;
    private javax.swing.JCheckBox cb_hobi_tidur;
    private javax.swing.JComboBox<String> cmb_agama;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelForm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelHobi;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableBio;
    private javax.swing.JRadioButton rb_jk_laki;
    private javax.swing.JRadioButton rb_jk_perempuan;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_notelp;
    // End of variables declaration//GEN-END:variables
  
}
